In [1]:
from subspace_est import subspace_estimation, subspace_estimation_helper
import numpy as np
import csv
import matplotlib.pyplot as plt
import scipy.io
import scipy.linalg

In [2]:
# Initialize d, K, M, T
T=20
d = 30;
K = 4;
rho = 0.5;

data = scipy.io.loadmat("data_LDS.mat")
mat = data['data']

In [3]:
data = mat.squeeze()
Msub= 30*d
data_subspace = data[:30*d]


In [4]:
new_data = np.zeros([Msub, d, T+1])
for i in range(Msub):
    new_data[i, :, :] = np.array(data_subspace[i])
print(new_data.shape)
V_i, U_i = subspace_estimation(new_data, K)

(900, 30, 21)
[  757.82414815   858.23719096  1061.60361686 18944.32465636]
[  763.44360229   875.94063099   984.39289673 19827.91829233]
[  648.04649104   682.25029875   779.13554436 15912.56511288]
[  786.09989898   886.00500927  1015.84807741 19794.33058705]
[  642.31945941   674.95016009   720.34423827 16890.10886983]
[  703.17650735   794.12844343   844.97302453 16359.43985709]
[  692.52031278   877.98491321   991.81127709 18026.12135861]
[  816.41526562   982.82661697  1261.95207525 22353.74984116]
[  647.20080699   717.11984993   992.67323032 17285.40598557]
[  664.17333319   798.68619131  1044.47876054 17166.96970842]
[  675.02567201   868.79059136   967.10966759 17707.48460022]
[  765.02845107   826.330084    1011.41065427 17163.67909486]
[  543.14534433   736.13080211   826.1332654  16017.52562525]
[  661.24539867   783.17365425   891.22058098 16929.9882004 ]
[  743.68762827   783.92472791   881.05851905 17480.93490922]
[  672.23170075   729.18402521   858.45987232 17772.8266

In [5]:
error_list = []
identity = np.eye(d)
for i in range(d):
    VVT = (V_i[i])@((V_i[i]).T)
    error_list.append(scipy.linalg.norm(identity - VVT, ord='fro'))

In [6]:
for i in range(d):
    UUT = (U_i[i])@((U_i[i]).T)
    error_list.append(scipy.linalg.norm(identity - UUT, ord='fro'))

In [8]:
np.max(V_i[0]), np.min(V_i[0])

(0.9915720004372489, -0.4097394641463258)