In [3]:
from subspace_est import subspace_estimation, subspace_estimation_helper
import numpy as np
import csv
import matplotlib.pyplot as plt
import scipy.io
import scipy.linalg

In [4]:
# Initialize d, K, M, T
T=20
d = 30;
K = 4;
rho = 0.5;

data = scipy.io.loadmat("data_LDS.mat")
mat = data['data']

In [5]:
data = mat.squeeze()
Msub= 30*d
data_subspace = data[:30*d]


In [6]:
new_data = np.zeros([Msub, d, T+1])
for i in range(Msub):
    new_data[i, :, :] = np.array(data_subspace[i])
print(new_data.shape)
V_i, U_i = subspace_estimation(new_data, K)

(900, 30, 21)
[ 0.90277457  0.9425377   1.05957318 21.36187675]
[1.06996058 1.28997132 1.47088659 1.81998586]
[ 0.89000829  1.02363385  1.20804386 23.03132536]
[1.46567369 1.70298376 1.74788516 2.32771592]
[ 0.65586553  0.70520993  0.8250731  17.97786106]
[0.95399556 1.22608449 1.59853491 2.43381033]
[ 0.7642116   0.90244474  1.26095196 22.30814506]
[0.928635   1.18920975 1.65714871 2.31347049]
[ 0.74509267  0.80132884  0.92920755 19.19591467]
[0.88808399 1.13230538 1.72420192 2.16708332]
[ 0.69966159  0.82015029  0.93205825 18.34182091]
[0.91785044 1.22950265 1.75740918 2.63698053]
[ 0.79309208  0.88988679  1.14440071 19.26082167]
[0.85892021 1.54252146 1.67655693 1.90388598]
[ 0.84010144  1.00292596  1.20687153 25.43715147]
[1.11462272 1.36632199 1.68469394 1.99010662]
[ 0.77648715  0.85576365  1.07570205 19.74699149]
[0.88390293 1.28105355 1.69489727 2.62081234]
[ 0.84557381  0.87462998  1.05719217 19.33674801]
[1.0327573  1.26474211 1.42126487 2.04778633]
[ 0.75280307  0.87946732  

In [7]:
error_list = []
identity = np.eye(d)
for i in range(d):
    VVT = (V_i[i])@((V_i[i]).T)
    error_list.append(scipy.linalg.norm(identity - VVT, ord='fro'))

In [8]:
for i in range(d):
    UUT = (U_i[i])@((U_i[i]).T)
    error_list.append(scipy.linalg.norm(identity - UUT, ord='fro'))

In [9]:
V_i.shape

(30, 30, 4)

In [10]:
H_i, G_i = subspace_estimation_helper(new_data)

In [11]:
printH_i[0]

array([[ 1.05401778e+01,  3.27502110e-01, -1.99229597e-01,
         2.24146590e-01, -1.51481902e-01,  1.96324990e-01,
        -6.76105120e-01, -5.00558564e-02,  2.88099183e-02,
        -1.55506752e-01, -3.86848898e-01, -5.76587877e-02,
         8.29767089e-02, -1.02771445e-01, -9.68028589e-02,
        -5.62885232e-01,  3.16895447e-01, -4.41454484e-02,
         1.98787908e-01,  3.79458881e-01,  1.01669236e-01,
        -1.40854800e-01, -2.43829266e-01, -3.48648071e-01,
        -3.05611082e-01,  6.58592167e-02,  2.64692166e-01,
         1.15315661e-01, -9.03113201e-02, -1.50235787e-01],
       [-2.87617374e-01,  6.40490753e-02, -1.12038771e-01,
        -5.32300352e-02, -4.21085340e-02,  6.71410161e-02,
         3.86635468e-02,  4.46673485e-04, -7.01839589e-02,
         3.33901594e-02,  6.04902218e-02,  6.15207022e-02,
         8.45658123e-02,  2.57069167e-02, -1.92715412e-02,
         2.01893136e-02, -6.94321876e-02, -1.86917603e-03,
         2.25746058e-02,  1.31865679e-02, -5.44535165e-